package BT_JList;

import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;

public class MyJList extends javax.swing.JFrame {

  DefaultListModel<HOCSINH> listModel = new DefaultListModel<HOCSINH>();

  public MyJList() {
    initComponents();
    load();

    ButtonGroup g = new ButtonGroup();
    g.add(nam);
    g.add(nu);

    myList.setModel(listModel);
    myList.setSelectedIndex(0);
  }

  public void load() {
    HOCSINH hs1 = new HOCSINH("Ninh", 5, true);
    HOCSINH hs2 = new HOCSINH("Ninh2", 6, true);
    listModel.addElement(hs1);
    listModel.addElement(hs2);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do
   * NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ten = new javax.swing.JTextField();
    diem = new javax.swing.JTextField();
    nam = new javax.swing.JRadioButton();
    nu = new javax.swing.JRadioButton();
    btnThem = new javax.swing.JButton();
    btnSua = new javax.swing.JButton();
    btnXoa = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    myList = new javax.swing.JList<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    nam.setText("Nam");

    nu.setText("Nu");

    btnThem.setText("Them");
    btnThem.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnThemActionPerformed(evt);
      }
    });

    btnSua.setText("Sua");
    btnSua.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSuaActionPerformed(evt);
      }
    });

    btnXoa.setText("Xoa");
    btnXoa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnXoaActionPerformed(evt);
      }
    });

    jLabel1.setText("Ten : ");

    jLabel2.setText("Diem :");

    myList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        myListValueChanged(evt);
      }
    });
    jScrollPane2.setViewportView(myList);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addComponent(btnThem)
            .addGap(28, 28, 28)
            .addComponent(btnSua)
            .addGap(31, 31, 31)
            .addComponent(btnXoa))
          .addGroup(layout.createSequentialGroup()
            .addComponent(nam)
            .addGap(18, 18, 18)
            .addComponent(nu))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(12, 12, 12))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(diem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(54, 54, 54)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(50, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(29, 29, 29)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(48, 48, 48)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(diem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(65, 65, 65))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nam)
          .addComponent(nu))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnThem)
          .addComponent(btnSua)
          .addComponent(btnXoa))
        .addGap(18, 18, 18))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void myListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_myListValueChanged
    int index = myList.getSelectedIndex();
    if (index < 0) {
      ten.setText("");
      diem.setText("");
      return;
    };

    HOCSINH hs = listModel.getElementAt(myList.getSelectedIndex());

    ten.setText(hs.ten);
    diem.setText(hs.diem + "");

    if (hs.phai == true) {
      nam.setSelected(true);
    } else {
      nu.setSelected(true);
    }
  }//GEN-LAST:event_myListValueChanged

  private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
    HOCSINH hs = new HOCSINH(ten.getText(), Integer.parseInt(diem.getText()), nam.isSelected());
    listModel.addElement(hs);
  }//GEN-LAST:event_btnThemActionPerformed

  private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
    int index = myList.getSelectedIndex();
    HOCSINH hs = listModel.getElementAt(index);

    hs.ten = ten.getText();
    hs.diem = Integer.parseInt(diem.getText());
    hs.phai = nam.isSelected();
    
//    Refresh list
    myList.setModel(listModel);
//    Reselect this modified item
    myList.setSelectedIndex(index);
  }//GEN-LAST:event_btnSuaActionPerformed

  private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
    int index = myList.getSelectedIndex();
    listModel.removeElementAt(index);
  }//GEN-LAST:event_btnXoaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MyJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MyJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MyJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MyJList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MyJList().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnSua;
  private javax.swing.JButton btnThem;
  private javax.swing.JButton btnXoa;
  private javax.swing.JTextField diem;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JList<HOCSINH> myList;
  private javax.swing.JRadioButton nam;
  private javax.swing.JRadioButton nu;
  private javax.swing.JTextField ten;
  // End of variables declaration//GEN-END:variables
}
