/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BT_JRadioBtn;

import java.awt.Color;

/**
 *
 * @author ninh
 */
public class MyFrame extends javax.swing.JFrame {

  /**
   * Creates new form MyFrame
   */
  public MyFrame() {
    initComponents();
    
    buttonGroup.add(btnCat);
    buttonGroup.add(btnBird);
    buttonGroup.add(btnDog);
    buttonGroup.add(btnPig);
    buttonGroup.add(btnRabbit);
    
  }

  /**
   * This method is called from within the constructor to initialize
   * the form. WARNING: Do NOT modify this code. The content of this
   * method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup = new javax.swing.ButtonGroup();
    rootPanel = new javax.swing.JPanel();
    btnCat = new javax.swing.JRadioButton();
    btnDog = new javax.swing.JRadioButton();
    btnBird = new javax.swing.JRadioButton();
    btnRabbit = new javax.swing.JRadioButton();
    btnPig = new javax.swing.JRadioButton();
    animalText = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnCat.setText("Cat");
    btnCat.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCatActionPerformed(evt);
      }
    });

    btnDog.setText("Dog");
    btnDog.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnDogActionPerformed(evt);
      }
    });

    btnBird.setText("Bird");
    btnBird.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBirdActionPerformed(evt);
      }
    });

    btnRabbit.setText("Rabbit");
    btnRabbit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRabbitActionPerformed(evt);
      }
    });

    btnPig.setText("Pig");
    btnPig.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPigActionPerformed(evt);
      }
    });

    animalText.setText("Result");

    javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
    rootPanel.setLayout(rootPanelLayout);
    rootPanelLayout.setHorizontalGroup(
      rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(rootPanelLayout.createSequentialGroup()
        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnCat)
          .addComponent(btnRabbit)
          .addComponent(btnPig))
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(rootPanelLayout.createSequentialGroup()
        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnBird)
          .addComponent(btnDog))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
        .addComponent(animalText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(24, 24, 24))
    );
    rootPanelLayout.setVerticalGroup(
      rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(rootPanelLayout.createSequentialGroup()
        .addComponent(btnCat)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(rootPanelLayout.createSequentialGroup()
            .addComponent(btnBird)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnDog))
          .addComponent(animalText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnRabbit)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnPig))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(123, 123, 123)
        .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(124, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(64, 64, 64)
        .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(72, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBirdActionPerformed
    this.animalText.setText("This is a Bird");
  }//GEN-LAST:event_btnBirdActionPerformed

  private void btnCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatActionPerformed
    this.animalText.setText("This is a Cat");
  }//GEN-LAST:event_btnCatActionPerformed

  private void btnDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDogActionPerformed
    this.animalText.setText("This is a Dog");
  }//GEN-LAST:event_btnDogActionPerformed

  private void btnRabbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRabbitActionPerformed
    this.animalText.setText("This is a Rabbit");
  }//GEN-LAST:event_btnRabbitActionPerformed

  private void btnPigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPigActionPerformed
    this.animalText.setText("This is a Pig");
  }//GEN-LAST:event_btnPigActionPerformed
  

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel animalText;
  private javax.swing.JRadioButton btnBird;
  private javax.swing.JRadioButton btnCat;
  private javax.swing.JRadioButton btnDog;
  private javax.swing.JRadioButton btnPig;
  private javax.swing.JRadioButton btnRabbit;
  private javax.swing.ButtonGroup buttonGroup;
  private javax.swing.JPanel rootPanel;
  // End of variables declaration//GEN-END:variables
}
