/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BT_JDialog;

/**
 *
 * @author ninh
 */
public class MyJFrame extends javax.swing.JFrame {

  /**
   * Creates new form MyJFrame
   */
  public MyJFrame() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize
   * the form. WARNING: Do NOT modify this code. The content of this
   * method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    rootPanel = new javax.swing.JPanel();
    textField = new javax.swing.JTextField();
    btnOpenDialog = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnOpenDialog.setText("Open Dialog");
    btnOpenDialog.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnOpenDialogActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
    rootPanel.setLayout(rootPanelLayout);
    rootPanelLayout.setHorizontalGroup(
      rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(rootPanelLayout.createSequentialGroup()
        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(rootPanelLayout.createSequentialGroup()
            .addGap(69, 69, 69)
            .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(rootPanelLayout.createSequentialGroup()
            .addGap(80, 80, 80)
            .addComponent(btnOpenDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(68, Short.MAX_VALUE))
    );
    rootPanelLayout.setVerticalGroup(
      rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(rootPanelLayout.createSequentialGroup()
        .addGap(29, 29, 29)
        .addComponent(btnOpenDialog)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
        .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(45, 45, 45))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(37, 37, 37)
        .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(37, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(52, 52, 52)
        .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(62, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnOpenDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenDialogActionPerformed

    MyJDialog dlg = new MyJDialog(this, true);
    dlg.setText(this.textField.getText());
    dlg.setVisible(true);
    
    this.textField.setText(dlg.getText());
  }//GEN-LAST:event_btnOpenDialogActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnOpenDialog;
  private javax.swing.JPanel rootPanel;
  private javax.swing.JTextField textField;
  // End of variables declaration//GEN-END:variables
}
